name: Build, Lint, e2e & ct test
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16.10.0
      - name: Install dependencies
        uses: cypress-io/github-action@v5.0.9
        with:
          runTests: false
  cypress-e2e-test:
  name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - uses: replayio/action-cypress@v0.2.7
        with:
          # An API key (usually a Team API Key) to use to upload replays.
          # Configure this via GitHub repo settings.
          api-key: rwk_r0HfdJBTl9IYKTS6LMg6BBG0RTVo7rcyVnLeoBA9uO8
          # The Replay browser to use: 'replay-firefox' or 'replay-chromium'
          browser: 'replay-chromium'
          # An optional command to run your tests.
          command: npm run cy:open-e2e
          # When true, replays will be accessible to anyone with the link.
          # This is useful for open source projects that want to collaborate
          # with external users.
          public: true
          # When true, replays of both passed and failed tests are uploaded
          upload-all: true
          # An optional working directory which is useful if the project being
          # tested resides in a subdirectory of the repository
          working-directory: .
